### ISSUE TITLE
JOSS paper submission

### ISSUE THREAD

**Issue by dirmeier** [kellylab/Fireworks#72]
Dear @smk508,

thanks for submitting to JOSS. Attached you'll find the first part of the review.

Regarding your paper there are only very minor comments ([here](https://www.dropbox.com/s/jpx9tei2ybenfpz/10.21105.joss.01478.pdf?dl=0)). 

Regarding the code and docu:
- It is very uncommon to name tools with a leading capital case letter in Python.
- Since the API is so big (and it's usage imho complex), I would find it useful to have more real-world use cases how a typical pipeline could look like. That is loading/preprocessing of data, builing a model, writing. You could, for instance, implement these use cases in Jupyter notebook (which users can then execute on [Binder](https://mybinder.org/)). Currently, while the documentation is very verbose, the practical use of (learning) your tool is not very clear to me.
- The repository contains  an `Rhistory` file.
- Most of the examples don't work due to `TypeError: 'no_grad' object is not callable`. I think this can be fixed by specifying a `torch` version in requirements.

Please let me know if there's something unclear.
Best, Simon

**Comment by smk508** [comment]
Hi @dirmeier ,
Thanks for the feedback. I'm going to figure out why the figure didn't show up in the paper and fix that. I'm also going to remove some of the random files in the repo and figure out why the examples didn't work for you. 
After that,  I can make an example notebook of a machine learning application to demonstrate a real-world use case.

thanks,
Saad

**Comment by dirmeier** [comment]
Cool, sounds great! 
Best,
Simon

**Comment by smk508** [comment]
Hi Simon,

I've updated the examples and made a Jupyter notebook demo for MNIST classification using fireworks. I've also cleaned up some of the files and descriptions in the README and documentation.

I don't know how to regenerate the PDF, but I fixed the typos in paper.md. I don't know why Figure 1 doesn't load, but the figure that's supposed to go there is in the paper/ directory as well.

Thanks,
Saad

**Comment by dirmeier** [comment]
Hey, could you try adding an exclamation mark in front? Like
```
![Figure 1.](Models.png)
```

Cheers,
S

**Comment by dirmeier** [comment]
One small comment:

I would really consider making the tutorials as notebooks altogether like [this](https://docs.pymc.io/notebooks/GLM-linear.html). That is no extra work and easily doable by adding [`nbsphinx`](https://nbsphinx.readthedocs.io/en/0.4.2/) to your `conf.py`. By that, users can just open it up a notebook in [binder](https://mybinder.org/v2/gh/kellylab/Fireworks/master?filepath=examples%2Fmnist.ipynb) and run it there.
In my experience users that see new software are way more likely to try it out if the docu is presented as notebooks, since they don't need to download and install the package.

Otherwise, if you prefer to rather provide `python` executables, could you please also refer to the notebook you made in the documentation, such that it is easy to find?

Thanks and cheers,
S

**Comment by smk508** [comment]
Ok I'll try that

**Comment by smk508** [comment]
Ok I made the tutorials into notebooks that can be accessed on Binder: https://gke.mybinder.org/v2/gh/kellylab/Fireworks/master
and I updated the docs to reference those notebooks as well.

**Comment by dirmeier** [comment]
Cool, great job!
